version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-event-manager
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - passin

  api-event-manager:
    build: 
      context: .
    container_name: api-event-manager
    entrypoint: sh -c './wait-for postgres:5432 -- pnpm db:migrate-deploy && pnpm start'
    ports:
      - 1502:1502
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - passin

networks:
  passin:
    driver: bridge

volumes:
  db: